### ISSUE TITLE
CRUSH Map viewer branding

### ISSUE THREAD

**Issue by a2batic** [rhcs-dashboard/ceph#29]
![screenshot from 2019-01-03 20-27-16](https://user-images.githubusercontent.com/12200504/50644172-14346580-0f96-11e9-8571-15042ce875c2.png)
![screenshot from 2019-01-03 20-27-01](https://user-images.githubusercontent.com/12200504/50644175-14ccfc00-0f96-11e9-8ed4-81f5a1674c01.png)

**Comment by julienlim** [comment]
@a2batic From a branding perspective, I don't know that there's anything in particular I want to call out.  However, from a UX perspective, I might suggest the following changes:
- The arrows are not consistent with the arrows in the application, e.g. navigation (see the arrows in the masthead which are outline vs. this one which is completely shaded).
- It would be nice if our selection used a cyan/blue selection vs. underline to be consistent with the rest of the application.
- If there are a lot of OSDs in a crush map bucket, e.g. ceph(host) in this example, when user scrolls it will be hard for user to know which crush map bucket the OSD belongs to.  It would be good to have some way to outline the selection, i.e. ceph(host) and it's children, when it's expanded to know what's in the bucket itself.  See list view expansion example at https://www.patternfly.org/pattern-library/content-views/list-view/.
- regarding the table on the right, is there any specific reason why the name, id, and type are not higher up in the table?  It just seems odd.  Not a showstopper, but user has selected the object on the left, and the property/config info shows up towards the bottom.
- does the crush map viewer also show the crush rulesets?

**Comment by julienlim** [comment]
@a2batic 
I've created a ceph tracker for the suggestions above at https://tracker.ceph.com/issues/37794.

The only item above that might be downstream focused is the arrow used as downstream seems to be the outline vs. the full shading in of the arrow (upstream).

**Comment by a2batic** [comment]
Closing this issue here.
